environment:
  PORT: ${PORT}
  DATABASE_URL: mongodb+srv://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}/cw-webhook-listener?tls=true&authSource=admin&replicaSet=${DATABASE_NAME}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_NAME: ${DATABASE_NAME}
  CA_CERT: ${CA_CERT}