environment:
  DATABASE_URL: "mongodb+srv://doadmin:6K27fPmL4u3c91o5@db-mongodb-nyc1-94101-a62cb87b.mongo.ondigitalocean.com/cw-webhook-listener?tls=true&authSource=admin&replicaSet=db-mongodb-nyc1-94101"
  PORT: 3000