environment:
  PORT: ${PORT}
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_NAME: ${DATABASE_NAME}
  CA_CERT: ${CA_CERT}